# Site settings
title: Gwt Bootstrap Tour
email: christian.mails@gmail.com
description: "A GWT wrapper for Bootstraptour JS library"
baseurl: "/gwt-bootstrap-tour"
url: "http://christianlacerda.github.io"
twitter_username: christianlacerd
github_username:  christianlacerda
project_version: 0.9.3

# Build settings
markdown: kramdown
permalink: pretty
